# Generated by Django 5.0.4 on 2024-04-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categorey_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories'),
        ),
    ]
