# Generated by Django 5.0.4 on 2024-04-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='received_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
