# Generated by Django 5.0.4 on 2024-04-26 10:05

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('storage', models.CharField(blank=True, max_length=300)),
                ('resolution', models.CharField(blank=True, max_length=200)),
                ('processer', models.CharField(blank=True, max_length=300)),
                ('GPU', models.CharField(blank=True, max_length=200)),
                ('OS', models.CharField(blank=True, max_length=100)),
                ('weight', models.FloatField(blank=True)),
                ('touchscreen', models.BooleanField(blank=True, default=False)),
                ('IPS', models.BooleanField(blank=True, default=False)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('actual_value', models.IntegerField(default=0)),
                ('expected_profit_value', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('product', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='product_images', to='store.product')),
            ],
        ),
    ]
