# Generated by Django 5.0.4 on 2024-04-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.JSONField(blank=True, default={'key': 'value'}),
            preserve_default=False,
        ),
    ]
