# Generated by Django 5.0.4 on 2024-04-16 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('actual_value', models.IntegerField(default=0)),
                ('expected_profit_value', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='store.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
