# Generated by Django 5.0.4 on 2024-04-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
